<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scope authorisation</title>
</head>

<body>

    <div class="wrapper" style="max-width:320px;margin:10vh auto;">
        <h1>Oauth scope authentication!</h1>
        <h4><?php echo "".$_SESSION["clientApplication"].""; ?> would like access to your account details please provide permission for the requested permissions below </h4>
        <p><?php echo $error[0] ?></p>

        <form method="post" action="localhost/oauth_server/authorisation_server/handle_scopes">
        <label for="scopes_array">Approve permissions</label><br>
            <?php
            foreach($allScopes as $scope) {
                echo "<input type='checkbox' checked='checked' name='scopes[]' value='$scope[id]' />$scope[description]<br />";
            }
            ?>
            <input type="submit" name="ApproveScopes" value="true" />
        </form>
    </div>

</body>

</html>